# Generated by Django 4.0.1 on 2022-01-12 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Splits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('datecreated', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_splits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Splittransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('datespent', models.DateField()),
                ('spentat', models.TextField()),
                ('mode', models.CharField(max_length=1)),
                ('spentby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_spentby', to=settings.AUTH_USER_MODEL)),
                ('spentfor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_spentfor', to=settings.AUTH_USER_MODEL)),
                ('splitid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_transactions', to='expenses.splits')),
            ],
        ),
        migrations.CreateModel(
            name='Splitmembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memeber_splits', to=settings.AUTH_USER_MODEL)),
                ('splitid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Split_members', to='expenses.splits')),
            ],
        ),
    ]
